### PR TITLE
Cpp11 compatibility

### LINKED ISSUE #76: cppdb and C++11: warning: ‘template<class> class std::auto_ptr’ is deprecated
compiling cppdb on a modern compiler (lastest gcc), gives off many such warnings: 

        warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]  

Basically, the code predates C++11.

### PR DESCRIPTION
**Pull request by dreaming-augustin**
This PR has the four following fixes, so that cppdb now compiles cleanly:

* 06f11bd Fix using integer constants in boolean context
* ab4ef1d  std::uncaught_exception() is deprecated
* 69600d3 Raise cmake_minimum_required to version 3.0
* 803ece0  C++11: std::auto_ptr => unique_ptr

Fixes: https://github.com/artyom-beilis/cppcms/issues/76

### CODE REVIEW

**Comment by dreaming-augustin** [comment]
In addition, the new cppdb repository does not have any tags nor releases.

CMakeLists.txt has:
```

set(CPPDB_MAJOR 0)
set(CPPDB_MINOR 3)
set(CPPDB_PATCH 1)

```
Version 0.3.1 is 11 years old!  48b0f1f 

Now that with this pull request,  cppdb compiles cleanly in a modern environment, should the version be bumped to 0.3.2 or 0.4.0?

**Comment by artyom-beilis** [comment]
> Now that with this pull request, cppdb compiles cleanly in a modern environment, should the version be bumped to 0.3.2 or 0.4.0?

No it should go to 1.0

Since moving to C++11 and adding bool option it breaks binary compatibility - thus new major version and so version needed.

- Major - breaking binary compatibility (i.e. you need to recompile to get updated so)
- Minor - backward binary compatibility - i.e. you added something but it is fully backward compatible
- Patch - just an updated that is both forward and backward compatible

I suggest don't add workaround for C++2003, I think we can safely move on and require C++11 by default - it is more than 10 years since C++11 was released. So in same way we don't need home-made mutex or home-made atomics.

**Comment by dreaming-augustin** [comment]
Please check the last two commits above.
It compiles cleanly.
Is that what you had in mind?
Did I miss anything?

What next?

**Comment by dreaming-augustin** [comment]
You also mentioned the following two items in the forum:
 
> * Add move ctor/assignment to most classes.
> * Maybe even check possibility of replacement of ref_ptr with shared_ptr (but this one is way more tricky and less nessary)

Is that something you'd like to be done in this branch, or should it be handled separately?
If it needs to be done, I will need assistance with these two, precise guidelines.

**Comment by artyom-beilis** [comment]
> Please check the last two commits above.
> It compiles cleanly.

Looks ok. 

> Add move ctor/assignment to most classes.

I think this can also help.

> Is that something you'd like to be done in this branch, or should it be handled separately?

No, there are many changes. As long as unit tests pass it is ok.

**Comment by artyom-beilis** [comment]
You can merge it.

**Comment by dreaming-augustin** [comment]
Thank you. :)

**Comment by dreaming-augustin** [comment]
None of the tags were imported from svn.

I added three tags as per comment above:
https://github.com/artyom-beilis/cppdb/tags 

tag: 0.3.1 = for reference, the last old stable version.
tag: 1.0.0-alpha = restart of development with MySQL 8.0 compatibility merge.
tag: 1.0.1-alpha = version set in CMakeLists.txt after the above merge.

**Pull request merged**
